name: Build Container Image
on: push
jobs:
  build:
    name: Build container image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set branch name
        id: repo
        run: echo "::set-output name=name::$(REPO_NAME=${GITHUB_REF##*/}; echo $REPO_NAME)"
      # - name: Build container image
      #   run: docker build . -t almahmoud/bioconductor_docker:${{ steps.branch.outputs.name }}
      - uses: almahmoud/r-notebook-container-build-action@master
        with:
          image-name: "almahmoud/bioconductor_docker"
          image-tag: ${{ steps.repo.outputs.name }}
          base-image: "bioconductor/bioconductor_docker"
          base-tag: "latest"
      - name: Login to DockerHub
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push to DockerHub with branch name
        uses: actions-hub/docker@master
        with:
          args: push almahmoud/bioconductor_docker:${{ steps.branch.outputs.name }}